-- AlterTable
ALTER TABLE "Order" ALTER COLUMN "subtotal" DROP DEFAULT,
ALTER COLUMN "tax" DROP DEFAULT,
ALTER COLUMN "total" DROP DEFAULT,
ALTER COLUMN "itemsInOrder" DROP DEFAULT,
ALTER COLUMN "isPaid" DROP DEFAULT;

-- AlterTable
ALTER TABLE "OrderItem" ALTER COLUMN "quantity" DROP DEFAULT,
ALTER COLUMN "price" DROP DEFAULT;
